name: testing

on:
  push:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Determine asset URLs for revision
        id: assets_urls
        uses: actions/github-script@0.9.0
        env:
          WORKFLOW_NAME: build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: string
          script: |
            return {
             darwin: {
               id: 4313844,
               node_id: 'MDg6QXJ0aWZhY3Q0MzEzODQ0',
               name: 'pack-darwin',
               size_in_bytes: 13478816,
               url: 'https://api.github.com/repos/jromero/pack/actions/artifacts/4313844',
               archive_download_url: 'https://api.github.com/repos/jromero/pack/actions/artifacts/4313844/zip',
               expired: false,
               created_at: '2020-04-13T20:22:33Z',
               updated_at: '2020-04-13T20:22:34Z'
             },
             linux: {
               id: 4313845,
               node_id: 'MDg6QXJ0aWZhY3Q0MzEzODQ1',
               name: 'pack-linux',
               size_in_bytes: 12414976,
               url: 'https://api.github.com/repos/jromero/pack/actions/artifacts/4313845',
               archive_download_url: 'https://api.github.com/repos/jromero/pack/actions/artifacts/4313845/zip',
               expired: false,
               created_at: '2020-04-13T20:22:33Z',
               updated_at: '2020-04-13T20:22:34Z'
             }
            }
      - name: Download artifact - darwin
        run: |
          curl -s -L \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -o pack-darwin.zip \
            ${{ steps.assets_urls.outputs.result.darwin }}
          unzip pack-darwin.zip -d pack-darwin
          chmod +x pack-darwin/pack
          tar -C pack-darwin -vzcf pack-darwin.tgz pack
      - name: Download artifact - linux
        run: |
          curl -s -L \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -o pack-linux.zip \
            ${{ steps.assets_urls.outputs.result.linux }}
          unzip pack-linux.zip -d pack-linux
          chmod +x pack-linux/pack
          tar -C pack-linux -vzcf pack-linux.tgz pack