name: testing

on:
  push:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Determine asset URLs for revision
        id: assets_urls
        uses: actions/github-script@0.9.0
        env:
          WORKFLOW_NAME: build
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return {
               darwin: 'https://api.github.com/repos/jromero/pack/actions/artifacts/4313844/zip',
               linux: 'https://api.github.com/repos/jromero/pack/actions/artifacts/4313845/zip'
             }
      - id: darwin_arifact
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.assets_urls.outputs.result }}
          url: "darwin"
      - name: Download artifact - darwin
        run: |
          curl -s -L \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -o pack-darwin.zip \
            ${{ steps.darwin_arifact.outputs.url }}
          unzip pack-darwin.zip -d pack-darwin
          chmod +x pack-darwin/pack
          tar -C pack-darwin -vzcf pack-darwin.tgz pack
      - id: linux_arifact
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.assets_urls.outputs.result }}
          url: "linux"
      - name: Download artifact - linux
        run: |
          curl -s -L \
            --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            -o pack-linux.zip \
            ${{ steps.linux_arifact.outputs.url }}
          unzip pack-linux.zip -d pack-linux
          chmod +x pack-linux/pack
          tar -C pack-linux -vzcf pack-linux.tgz pack